### ISSUE TITLE
Autocompletion doesn't work

### ISSUE THREAD

**Issue by icewind** [tailwindlabs/tailwindcss-intellisense#639]
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.9.1

**What version of Tailwind CSS are you using?**

For example: v3.2.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

After the last update, autocompletion stopped to work in both neovim(using nvim lspconfig) and VSCode. There is an error in the logs(the error is the same in nvim and VSCode)
```
[ERROR][2022-10-20 19:09:47] ...lsp/handlers.lua:485	
Tailwind CSS: Cannot read properties of undefined (reading 'modifier')
TypeError: Cannot read properties of undefined (reading 'modifier')
    at api.addVariant (/Users/icewind/Projects/TailwindTest/app/node_modules/tailwindcss/lib/lib/setupContextUtils.js:578:40)
    at /Users/icewind/Projects/TailwindTest/app/node_modules/tailwindcss/lib/lib/setupContextUtils.js:538:38
    at /usr/local/lib/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:695:4338
    at Array.forEach (<anonymous>)
    at QMe (/usr/local/lib/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:695:3823)
    at /usr/local/lib/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:695:283
    at Generator.next (<anonymous>)
    at i (/usr/local/lib/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:2:1059)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by reinink** [comment]
Hey maybe try restarting VS Code? This issue should be resolved in the latest version of the Intellisense plugin 👍

**Comment by icewind** [comment]
> Hey maybe try restarting VS Code? This issue should be resolved in the latest version of the Intellisense plugin 👍

I tried to restart VSCode several times. No luck. 
<img width="646" alt="Screenshot 2022-10-20 at 21 30 32" src="https://user-images.githubusercontent.com/575985/197018272-117677f7-ad42-4dda-a073-bf4bfc7d0ac5.png">

**Comment by bradlc** [comment]
Please can you share the full text from the output panel? (`Tailwind CSS: Show Output` command to reveal)

**Comment by icewind** [comment]
That is weird. I reinstalled the plugin and the language server and now the error is gone(only in VSCode) but it still not working. `Tailwind CSS: Show Output` shows that it is stuck in a building phase. I created fresh project and here is the output
```
[Global] Creating projects: [{"folder":"/Users/icewind/Temp/tailwind_plugin_test","configPath":"/Users/icewind/Temp/tailwind_plugin_test/tailwind.config.cjs","isUserConfigured":false,"documentSelector":[{"pattern":"/Users/icewind/Temp/tailwind_plugin_test/tailwind.config.cjs","priority":0},{"pattern":"/Users/icewind/Temp/tailwind_plugin_test/index.html","priority":1},{"pattern":"/Users/icewind/Temp/tailwind_plugin_test/src/**/*.{js,ts,jsx,tsx}","priority":1},{"pattern":"/Users/icewind/Temp/tailwind_plugin_test/**","priority":3}]}]
[Global] Adding watch patterns: /Users/icewind/Temp/tailwind_plugin_test/tailwind.config.cjs, /Users/icewind/Temp/tailwind_plugin_test, /Users/icewind/Temp, /Users/icewind, /Users, /
[tailwind.config.cjs] Initializing...
[tailwind.config.cjs] Loaded Tailwind CSS config file: /Users/icewind/Temp/tailwind_plugin_test/tailwind.config.cjs
[tailwind.config.cjs] Loaded postcss v8.4.18: /Users/icewind/Temp/tailwind_plugin_test/node_modules/postcss
[tailwind.config.cjs] Loaded tailwindcss v3.2.0: /Users/icewind/Temp/tailwind_plugin_test/node_modules/tailwindcss
[tailwind.config.cjs] Building...
```

**Comment by icewind** [comment]
Tried to reinstall everything once again and it is working... Probably there is an issue on my side. But updating ` @tailwindcss/language-server` definitely helped. Thank you for your work!
