### ISSUE TITLE
Intellisense not working on Windows for some projects / setups (v0.12.x)

### ISSUE THREAD

**Issue by emirefek** [tailwindlabs/tailwindcss-intellisense#988]
**Maintainer's note:**

### v0.12.5 has been published please update and give it a test first

---

**What version of VS Code are you using?**
v1.90.2

**What version of Tailwind CSS IntelliSense are you using?**
v0.12.0

**What version of Tailwind CSS are you using?**
v3.4.4

**What package manager are you using?**
npm

**What operating system are you using?**
Windows

**Tailwind config**
```js
import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/views/**/*.blade.php",
    "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    "./vendor/laravel/jetstream/**/*.blade.php",
    "./storage/framework/views/*.php",
  ],

  theme: {
    extend: {
      fontFamily: {
        sans: ["Figtree", ...defaultTheme.fontFamily.sans],
      },
    },
  },

  plugins: [forms, typography],
};

```

**VS Code settings**

```json
previous version works so I don't really wanna spend time to remove unrelated stuff from it.
```

**Describe your issue**
After last vscode extension update, it stoped working.

**Comment by darklight9811** [comment]
Same for me, I noticed not every project stopped working, but every monorepo project has stopped working.

**Comment by darklight9811** [comment]
Just wasted 2 hours trying to figure this out...

**Comment by mpkr** [comment]
I have the same issue, it works in 0.10.5 but the latest one

**Comment by HyunJinNo** [comment]
I have the same issue. It doesn't work in 0.12.0 on my window 11.

**Comment by mrfrost1110** [comment]
I'm having the same issue with v0.12.0 on Windows. Rolling back to v0.10.5 worked for me.

**Comment by etiennewayne** [comment]
I experienced the same issue for the updated v0.12.0, at first, I thought it was a conflict from other extensions, Rolling back to v0.10.5 solved.

**Comment by zexzeq** [comment]
Same for v0.12.0, Windows 10, VS Code 1.90.2.

Version 0.10.5 is ok.

**Comment by FredTreg** [comment]
Same for me: v0.12.0 does not work (Windows 10 + Dev containers), VS Code 1.90.2

Version 0.10.5 works

**Comment by konalt** [comment]
Me too: v0.12.0 does not work on network drives. VS Code 1.90.2

**Comment by dav1ee** [comment]
Same for me with 0.12.0, had to downgrade to 0.10.5 to get it working again

**Comment by Tubig-Repo** [comment]
downgrade it an older version it worked for me

**Comment by ayrtonandino** [comment]
For me it broke the little preview that shows what CSS is applying, when you hover over the class.

![classPreview](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/60512432/8cd190b7-2fc2-4e9d-8638-99f6b7ff626a)

I didn't know how much I rely on that.

**Comment by joedave13** [comment]
Mine's also not working with version 0.12.0, downgrade to 0.10.5 solve the problem for now

**Comment by belicks1999** [comment]
for me also its not working

**Comment by ndozhh** [comment]
I have the same problem. 0.10.5 intelisense is working but only in the folder that contains the `tailwind.config.ts` file. I have a monorepo where `tailwind.config.ts` is located in `apps/web`, but now using `0.10.5` the autocomplete and hover class translation only work for `apps/web`. Files in `ui` are taking the classes but neither autocomplete nor hover class translation are working.

```
content: [
    './app/**/*.{js,jsx,ts,tsx}',
    '../../packages/ui/**/*.{js,ts,jsx,tsx}',
    '../docs/stories/*.{ts,tsx,js,jsx}',
  ],
```

File in `packages/ui`
![error](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/25773289/a4f3b02e-9542-4068-a8f0-49574a471f80)

**Comment by xt0rted** [comment]
Looking at the log output of v0.12.0 this seems like it's due to path normalization which should be fixed by #980.

**Comment by thecrypticace** [comment]
I'm working on pushing out a release with that fix right now

**Comment by thecrypticace** [comment]
**v0.12.1 has been published please give it a test**

**Comment by thecrypticace** [comment]
Added a note to try the update in the original issue/comment at the top

**Comment by ndozhh** [comment]
@thecrypticace `0.12.1` is working thank you, but do you have any advice to debug why autocomplete not working in other packages outside where `tailwind.config.ts` is defined?. I don't know when it stopped working but yesterday I saw it's not working anymore. I think a month ago it was working well, any ideas? Thank you

**Comment by xt0rted** [comment]
If you find you're still not getting IntelliSense on Windows with v0.12.1 double check that the folder path used when opening VSCode matches what's on disk. If those don't match then this extension, and many others probably, won't work correctly.

When I first ran into this issue I was opening my workspace from GitHub Desktop which had a path casing that didn't match what was on disk. GitHub Desktop had `c:\dev\project` but on disk it was `c:\Dev\Project`.

I ran into this a second time with my pinned workspace in the task bar. Right click on the VSCode icon and hovering over my pinned workspace showed casing that also didn't match what was on disk. Un-pin, re-open, re-pin the workspace and everything worked again.

**Comment by thecrypticace** [comment]
@ndozhh I would've assumed it was a bug in v0.12.x that's causing it but given that you mentioned that it's also broken in v0.10.5 — maybe a VSCode update? I'm not sure. I would check what @xt0rted mentioned and see if you see anything different there.

Any chance you can provide a reproduction repo that I can look at? Intellisense issues are notoriously complicated (and sometimes impossible) to debug without them.

I'm going to look into this and see if I can figure out a workaround because that behavior is rather unfortunate. Only problem is some filesystems are case-sensitive (kinda wish they all were tbh) and some are not so I can't just blindly lowercase everything.

**Comment by darklight9811** [comment]
0.12.1 fixed it for me

**Comment by thecrypticace** [comment]
🙌 🙌 fantastic. I'll leave this issue open for another day and if more people report in that it's fixed I'll close it.

**Comment by ayrtonandino** [comment]
> 0.12.1 fixed it for me

same

**Comment by binaryartifex** [comment]
mines cactus still. nx monorepo, been working smoothly all year till this new version. i have a root workspace config file that all app configs inherit from. i have a common ui folder that inherits from the workspace tailwind config, and any files within the apps or libs namespaced below have their appropriate tailwind configs.

vscode settings

```json
  "tailwindCSS.experimental.configFile": {
    "tailwind-workspace-preset.ts": ["libs/common/ui/**"],
    "apps/app-1/app/tailwind.config.ts": ["apps/app-1/app/**", "libs/app-1/**"],
    "apps/app-2/app/tailwind.config.ts": ["apps/app-2/app/**", "libs/app-2/**"],
    "apps/app-3/tailwind.config.ts": ["apps/app-3/app/**", "libs/app-3/**"]
  },
  "tailwindCSS.classAttributes": ["class", "className", ".*Styles.*"],
  "tailwindCSS.experimental.classRegex": [
    [
      "tv\\(([^)(]*(?:\\([^)(]*(?:\\([^)(]*(?:\\([^)(]*\\)[^)(]*)*\\)[^)(]*)*\\)[^)(]*)*)\\)",
      "\"(.*?)\""
    ]
  ],
  "tailwindCSS.files.exclude": [
    "**/.git/**",
    "**/dist/**",
    "**/node_modules/**",
    "**/.nx/**",
    "**/.husky/**",
    "**/pnpm-lock.yaml"
  ]
```

prettier

```json
{
  "arrowParens": "always",
  "bracketSameLine": false,
  "bracketSpacing": true,
  "endOfLine": "auto",
  "printWidth": 100,
  "tabWidth": 2,
  "singleQuote": false,
  "trailingComma": "all",
  "plugins": ["prettier-plugin-tailwindcss"],
  "tailwindConfig": "tailwind-workspace-preset.ts"
}
```

**Comment by ndozhh** [comment]
> @ndozhh I would've assumed it was a bug in v0.12.x that's causing it but given that you mentioned that it's also broken in v0.10.5 — maybe a VSCode update? I'm not sure. I would check what @xt0rted mentioned and see if you see anything different there.
> 
> Any chance you can provide a reproduction repo that I can look at? Intellisense issues are notoriously complicated (and sometimes impossible) to debug without them.
> 
> I'm going to look into this and see if I can figure out a workaround for the casing-difference behavior because it's rather unfortunate. Only problem is some filesystems are case-sensitive (kinda wish they all were tbh) and some are not so I can't just blindly lowercase everything.

@thecrypticace It's working now. The solution was to add an empty `tailwind.config.ts` file and a `postcss.config.js` file to my `packages/ui` and autocomplete works well now. I don't know why it was working before without those. Btw I tried this after having created the reproduction you asked for and notice it was working there. Thanks for the help!

**Comment by etiennewayne** [comment]
> **v0.12.1 has been published please give it a test**

It's working, Thanks

**Comment by bturski** [comment]
Updating to v0.12.1 fixed intellisense for me.
I had downgraded from v0.12.0 back to v0.10.5 and intellisense was working. I updated to v0.12.1 and restarted extensions but was still broken. Intellisense didn't start working again until I completely closed and re-opened VSCode.

**Comment by ToxicCrack** [comment]
Updating to 0.12.1 didn't fixed it for me (Linux). Only 0.10 is working

**Comment by FrancescoLuzzi** [comment]
@thecrypticace `0.12.1` doesn't work for me, my project is located in a network drive and the `tailwind.config.js` file path gets mangled.

I have mapped `RedactedServer` to my `K:` drive, when trying to open `tailwind.config.js` the `K:` is prepended to the `UNC` path.

Here is the server log:
```text
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":true}}
[Global] Creating projects: [{"folder":"K:\\Projects\\test","config":"/RedactedServer/Projects/test/tailwind.config.js","selectors":[{"pattern":"/RedactedServer/Projects/test/tailwind.config.js","priority":0},{"pattern":"/RedactedServer/Projects/test/**","priority":3},{"pattern":"K:/Projects/test/**","priority":4},{"pattern":"K:/Projects/test/**","priority":5}],"user":false,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":true}}]
[Global] Adding watch patterns: /RedactedServer/Projects/test/tailwind.config.js, /RedactedServer/Projects/test, /RedactedServer/Projects, /RedactedServer, /
[..\RedactedServer\Projects\test\tailwind.config.js] Initializing...
[Error - 10:17:28 AM] Tailwind CSS: ENOENT: no such file or directory, stat 'k:\RedactedServer\Projects\test\tailwind.config.js'
```

**Comment by tratteo** [comment]
Same here, broken on version > v0.11.80.
I rolled back to v0.11.80 and issue was fixed for the moment.

**Comment by binaryartifex** [comment]
@thecrypticace gday mate sorry for the late reply, so ive switched back to 0.12.1, completely closed and restarted vscode with the following output, it looks like the process freezes after the watch processes are in place, it goes no further than there

```bash
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"f:\\[directory]","config":"f:/[directory]/tailwind-workspace-preset.ts","selectors":[{"priority":0,"pattern":"f:/[directory]/libs/common/ui/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"f:\\[directory]\\temp\\spectrum","config":"f:/[directory]/apps/app-1/app/tailwind.config.ts","selectors":[{"priority":0,"pattern":"f:/[directory]/apps/app-1/app/**"},{"priority":0,"pattern":"f:/[directory]/libs/app-1/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"f:\\[directory]\\temp\\spectrum","config":"f:/[directory]/apps/app-2/app/tailwind.config.ts","selectors":[{"priority":0,"pattern":"f:/[directory]/apps/app-2/app/**"},{"priority":0,"pattern":"f:/[directory]/libs/app-2/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"f:\\[directory]\\temp\\spectrum","config":"f:/[directory]/apps/app-3/tailwind.config.ts","selectors":[{"priority":0,"pattern":"f:/[directory]/apps/app-3/**"},{"priority":0,"pattern":"f:/[directory]/libs/app-3/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Adding watch patterns: f:/[directory]/tailwind-workspace-preset.ts, f:/[directory], f:/[directory]/temp, f:/[directory], f:/client-projects, f:/, f:/[directory]/tailwind-workspace-preset.ts, f:/[directory], f:/[directory]/temp, f:/[directory], f:/client-projects, f:/
[Global] Adding watch patterns: f:/[directory]/apps/app-1/app/tailwind.config.ts, f:/[directory]/apps/app-1/app, f:/[directory]/apps/app-1, f:/[directory]/apps, f:/[directory]/apps/app-1/app/tailwind.config.ts, f:/[directory]/apps/app-1/app, f:/[directory]/apps/app-1, f:/[directory]/apps
[Global] Adding watch patterns: f:/[directory]/apps/app-2/app/tailwind.config.ts, f:/[directory]/apps/app-2/app, f:/[directory]/apps/app-2, f:/[directory]/apps/app-2/app/tailwind.config.ts, f:/[directory]/apps/app-2/app, f:/[directory]/apps/app-2
[Global] Adding watch patterns: f:/[directory]/apps/app-3/tailwind.config.ts, f:/[directory]/apps/app-3, f:/[directory]/apps/app-3/tailwind.config.ts, f:/[directory]/apps/app-3
```

using the following config in my workspace settings.json

```json
}
  "tailwindCSS.experimental.configFile": {
    "tailwind-workspace-preset.ts": ["libs/common/ui/**"],
    "apps/app-1/app/tailwind.config.ts": ["apps/app-1/app/**", "libs/app-1/**"],
    "apps/app-2/app/tailwind.config.ts": [
      "apps/app-2/app/**",
      "libs/app-2/**"
    ],
    "apps/app-3/tailwind.config.ts": ["apps/app-3/**", "libs/app-3/**"]
  },
  "tailwindCSS.classAttributes": ["class", "className", ".*Styles.*"],
  "tailwindCSS.experimental.classRegex": [
    [
      "tv\\(([^)(]*(?:\\([^)(]*(?:\\([^)(]*(?:\\([^)(]*\\)[^)(]*)*\\)[^)(]*)*\\)[^)(]*)*)\\)",
      "\"(.*?)\""
    ]
  ],
  "tailwindCSS.files.exclude": [
    "**/.git/**",
    "**/dist/**",
    "**/node_modules/**",
    "**/.nx/**",
    "**/.husky/**",
    "**/pnpm-lock.yaml"
  ]
}
```

**Comment by thecrypticace** [comment]
@binaryartifex I have a feeling you might be on a networked drive. Mind updating to v0.12.2?

@ToxicCrack Can you update to v0.12.2? If that doesn't work can you open an issue with details about your environment and logs and what not?

@FrancescoLuzzi v0.12.2 should fix this

@tratteo Can you provide more details?

**Comment by FrancescoLuzzi** [comment]
@thecrypticace can confirm, `0.12.2` resolves the network drive issue, thank you!

**Comment by binaryartifex** [comment]
gah dammit. nah no dice for me im afraid. the drive im using isn't the drive my OS is on, ive got a drive dedicated to dev work but isn't part of a wider network or isolated in any way. Same issue, gets as far as the watch processes like the logs above and freezes. im managing multiple config files derived from a workspace config that isn't named conventionally, has there been a change between versions that manages that any differently?

**Comment by thecrypticace** [comment]
@binaryartifex I'll see what I can figure out. I might need to add more logging. It seems weird that v0.12.0 would've worked for you where v0.12.1 does not given the only difference between them is making sure the drive-letter casing matches between vscode and the filesystem.

**Comment by ToxicCrack** [comment]
@thecrypticace 0.12.2 is also working on Linux now! Thanks

**Comment by tratteo** [comment]
I did some tests and for me **any version above 0.12.0 breaks the intellisense on Vscode**. 
**I am currently using v0.12.0 and it is working fine.**

**Comment by joshuabalentine-PCC** [comment]
@thecrypticace version 0.12.* broke intellisense for me on Windows as well. After seeing @xt0rted's note about file paths matching, I was able to get it working again.

I have a DevDrive set up on my machine as drive E:. I've mapped it to a folder in my user profile C:\Users\[my profile]\Source, so VS Code was opening folder C:\Users\[my profile]\Source\[project path] and the extension was finding the tw config file at E:\[project path]\tailwind.config.js causing the mismatch.

Opening VS Code on folder E:\[project path] directly got intellisense working again.

**Comment by Mirthis** [comment]
Broken for me for any version above `0.12.0`.
Newer versions work ok on the same code base but under WSL rather than native Windows.
I can clearly see the difference in the Output tab of VS Code under `Tailwind CSS Intellisense` as on windows the logs never show anything after `Adding watch patterns`.

**Comment by thecrypticace** [comment]
@joshuabalentine-PCC Mind detailing how you set that up? I'd love to reproduce this so I can see if it's something I can potentially fix. I tried doing the same thing and it seems to work in v0.12.2:
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
[Global] Creating projects: [{"folder":"C:\\Users\\jordanpittman\\DevDriveMount\\netshare","config":"E:/netshare/tailwind.config.js","selectors":[{"pattern":"E:/netshare/tailwind.config.js","priority":0},{"pattern":"E:/netshare/**","priority":3},{"pattern":"C:/Users/jordanpittman/DevDriveMount/netshare/**","priority":5}],"user":false,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Adding watch patterns: E:/netshare/tailwind.config.js, E:/netshare, E:/, E:/netshare/tailwind.config.js, E:/netshare, E:/
[E:\netshare\tailwind.config.js] Initializing...
[E:\netshare\tailwind.config.js] supported features: ["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"]
[E:\netshare\tailwind.config.js] Loaded tailwindcss v3.4.4: E:\netshare\node_modules\tailwindcss
[E:\netshare\tailwind.config.js] Loaded Tailwind CSS config file: E:/netshare/tailwind.config.js
[E:\netshare\tailwind.config.js] Loaded postcss v8.4.38: E:\netshare\node_modules\postcss
[E:\netshare\tailwind.config.js] Building...
```

**Comment by thecrypticace** [comment]
@Mirthis @tratteo @binaryartifex I think it's likely that you are all running into the same issue — I'm just not sure what that is currently.

I've merged in a change that makes some tweaks and adds logging that should go out in our pre-release build in the next 10 minutes or so. Mind giving it a test and providing the logs? They'll be a bit noisy but I'm hoping it'll help me figure out where things are getting stuck because I'm having trouble reproducing these issues. Really, really appreciate the patience here!

**Comment by joshuabalentine-PCC** [comment]
I'm running Windows 11, so under Settings > System > Storage (> Advanced) > Disks & volumes, I created the Dev Drive partition, then once it was made, in the same Settings page, select that drive's Properties, there's a Paths section to mount it into the primary NTFS drive.

I'm running VS Code 1.90.2 with the following extensions:
- visualstudioexptteam.vscodeintellicode v1.3.1
- visualstudioexptteam.intellicode-api-usage-examples v0.2.8
- cpylua.language-postcss v1.1.0
- ms-vsliveshare.vsliveshare v1.0.5932
- bradlc.vscode-tailwindcss v0.12.2
- vue.volar v2.0.22

My project is a Vue application that builds with webpack. It builds one way into a library folder and another way into a public folder, so the Tailwind extension is picking up 3 tailwind projects.

When I open the folder C:\Users\JoshuaBalentine\Source\\[project] in VS Code, the Tailwind extension has this output:
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
[Global] Creating projects: [{"folder":"C:\\Users\\JoshuaBalentine\\Source\\[project]","config":"E:/[project]/library/static/dist/js/tailwind.js","selectors":[{"pattern":"E:/[project]/library/static/dist/js/tailwind.js","priority":0},{"pattern":"E:/[project]/library/static/dist/js/**","priority":3},{"pattern":"E:/[project]/**","priority":4}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"C:\\Users\\JoshuaBalentine\\Source\\[project]","config":"E:/[project]/public/static/dist/js/tailwind.js","selectors":[{"pattern":"E:/[project]/public/static/dist/js/tailwind.js","priority":0},{"pattern":"E:/[project]/public/static/dist/js/**","priority":3},{"pattern":"E:/[project]/**","priority":4}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"C:\\Users\\JoshuaBalentine\\Source\\[project]","config":"E:/[project]/tailwind.config.js","selectors":[{"pattern":"E:/[project]/tailwind.config.js","priority":0},{"pattern":"E:/[project]/src/**/*.{js,vue}","priority":1},{"pattern":"E:/[project]/fractal/**/*.{js,hbs}","priority":1},{"pattern":"E:/[project]/src/assets/css/**/*.css","priority":1},{"pattern":"E:/[partial project]/**/*.cshtml","priority":1},{"pattern":"E:/[project]/**","priority":3}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Adding watch patterns: E:/[project]/library/static/dist/js/tailwind.js, E:/[project]/library/static/dist/js, E:/[project]/library/static/dist, E:/[project]/library/static, E:/[project]/library, E:/[project], E:/[partial project], E:/, E:/[project]/library/static/dist/js/tailwind.js, E:/[project]/library/static/dist/js, E:/[project]/library/static/dist, E:/[project]/library/static, E:/[project]/library, E:/[project], E:/[partial project], E:/
[Global] Adding watch patterns: E:/[project]/public/static/dist/js/tailwind.js, E:/[project]/public/static/dist/js, E:/[project]/public/static/dist, E:/[project]/public/static, E:/[project]/public, E:/[project]/public/static/dist/js/tailwind.js, E:/[project]/public/static/dist/js, E:/[project]/public/static/dist, E:/[project]/public/static, E:/[project]/public
[Global] Adding watch patterns: E:/[project]/tailwind.config.js, E:/[project]/tailwind.config.js
```

When I open the folder E:\\[project] in VS Code, the Tailwind extension has this output:
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
[Global] Creating projects: [{"folder":"E:\\[project]","config":"E:/[project]/library/static/dist/js/tailwind.js","selectors":[{"pattern":"E:/[project]/library/static/dist/js/tailwind.js","priority":0},{"pattern":"E:/[project]/library/static/dist/js/**","priority":3},{"pattern":"E:/[project]/**","priority":4}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"E:\\[project]","config":"E:/[project]/public/static/dist/js/tailwind.js","selectors":[{"pattern":"E:/[project]/public/static/dist/js/tailwind.js","priority":0},{"pattern":"E:/[project]/public/static/dist/js/**","priority":3},{"pattern":"E:/[project]/**","priority":4}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"E:\\[project]","config":"E:/[project]/tailwind.config.js","selectors":[{"pattern":"E:/[project]/tailwind.config.js","priority":0},{"pattern":"E:/[project]/src/**/*.{js,vue}","priority":1},{"pattern":"E:/[project]/fractal/**/*.{js,hbs}","priority":1},{"pattern":"E:/[project]/src/assets/css/**/*.css","priority":1},{"pattern":"E:/[partial project]/**/*.cshtml","priority":1},{"pattern":"E:/[project]/**","priority":3}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Adding watch patterns: E:/[project]/library/static/dist/js/tailwind.js, E:/[project]/library/static/dist/js, E:/[project]/library/static/dist, E:/[project]/library/static, E:/[project]/library, E:/[project], E:/[partial project], E:/, E:/[project]/library/static/dist/js/tailwind.js, E:/[project]/library/static/dist/js, E:/[project]/library/static/dist, E:/[project]/library/static, E:/[project]/library, E:/[project], E:/[partial project], E:/
[Global] Adding watch patterns: E:/[project]/public/static/dist/js/tailwind.js, E:/[project]/public/static/dist/js, E:/[project]/public/static/dist, E:/[project]/public/static, E:/[project]/public, E:/[project]/public/static/dist/js/tailwind.js, E:/[project]/public/static/dist/js, E:/[project]/public/static/dist, E:/[project]/public/static, E:/[project]/public
[Global] Adding watch patterns: E:/[project]/tailwind.config.js, E:/[project]/tailwind.config.js
[tailwind.config.js] Initializing...
[tailwind.config.js] supported features: ["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"]
[tailwind.config.js] Loaded tailwindcss v3.4.3: E:\[project]\node_modules\tailwindcss
[tailwind.config.js] Loaded Tailwind CSS config file: E:/[project]/tailwind.config.js
[tailwind.config.js] Loaded postcss v8.4.38: E:\[project]\node_modules\postcss
[tailwind.config.js] Building...
```

**Comment by joshuabalentine-PCC** [comment]
@thecrypticace On your prerelease version `0.13.5`, the `[GLOBAL] Checking document` statements use the C drive path and the `[GLOBAL] Checking selectors` statements use the E drive path. Also, there's a statement `[Global] Initialized 0 projects`

**Comment by Mirthis** [comment]
> @Mirthis @tratteo @binaryartifex I think it's likely that you are all running into the same issue — I'm just not sure what that is currently.
> 
> I've merged in a change that makes some tweaks and adds logging that should go out in our pre-release build in the next 10 minutes or so. Mind giving it a test and providing the logs? They'll be a bit noisy but I'm hoping it'll help me figure out where things are getting stuck because I'm having trouble reproducing these issues. Really, really appreciate the patience here!

@thecrypticace not sure this is what you're after but here it is.
Also let me know if you need any other specific detail related to my setup.

v0.12.0 - working fine
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"c:\\Users\\mirth\\Coding\\simple-day-planner","config":"c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts","selectors":[{"priority":0,"pattern":"c:/Users/mirth/Coding/simple-day-planner/**"}],"user":true,"tailwind":{"version":"3.4.1","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Adding watch patterns: c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/base.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/
[tooling\tailwind\web.ts] Initializing...
[tooling\tailwind\web.ts] supported features: ["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"]
[tooling\tailwind\web.ts] Loaded tailwindcss v3.4.1: c:\Users\mirth\Coding\simple-day-planner\node_modules\tailwindcss
[tooling\tailwind\web.ts] Loaded Tailwind CSS config file: c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts
[tooling\tailwind\web.ts] Loaded postcss v8.4.35: c:\Users\mirth\Coding\simple-day-planner\node_modules\postcss
[tooling\tailwind\web.ts] Building...
```

v0.12.2 - not working
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"c:\\Users\\mirth\\Coding\\simple-day-planner","config":"c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts","selectors":[{"priority":0,"pattern":"c:/Users/mirth/Coding/simple-day-planner/**"}],"user":true,"tailwind":{"version":"3.4.1","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Adding watch patterns: c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/base.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/
```

v0.13.5 (pre-release) - also not working
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"c:\\Users\\mirth\\Coding\\simple-day-planner","config":"c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts","selectors":[{"priority":0,"pattern":"c:/Users/mirth/Coding/simple-day-planner/**"}],"user":true,"tailwind":{"version":"3.4.1","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Adding watch patterns: c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/web.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind/base.ts, c:/Users/mirth/Coding/simple-day-planner/tooling/tailwind, c:/Users/mirth/Coding/simple-day-planner/tooling, c:/Users/mirth/Coding/simple-day-planner, c:/Users/mirth/Coding, c:/Users/mirth, c:/Users, c:/
[Global] Initializing projects...
[GLOBAL] Checking selectors [
  {
    priority: 0,
    pattern: 'c:/Users/mirth/Coding/simple-day-planner/**'
  }
]
[GLOBAL] Checking document {
  fsPath: 'C:\\Users\\mirth\\Coding\\simple-day-planner\\apps\\nextjs\\src\\components\\activities\\ActivityCard.tsx',
  normalPath: '/c:/Users/mirth/Coding/simple-day-planner/apps/nextjs/src/components/activities/ActivityCard.tsx'
}
[Global] Initialized 0 projects
```

**Comment by thecrypticace** [comment]
Ah — I think I know what it might be! Lemme verify (may take a bit)

**Comment by thecrypticace** [comment]
@joshuabalentine-PCC wild this is exactly how I set mine up (aside from the path being just slightly different) 😱 — I'll keep looking into it

**Comment by thecrypticace** [comment]
@Mirthis Try the latest pre-release when you get a chance? Hopefully I've figured it out 🙏

**Comment by binaryartifex** [comment]
@thecrypticace can confirm latest pre-release works like a charm mate, solid effort👍

**Comment by thecrypticace** [comment]
🙌 🙌

**Comment by thecrypticace** [comment]
I'll look at tagging a new release in the morning

**Comment by Mirthis** [comment]
> @Mirthis Try the latest pre-release when you get a chance? Hopefully I've figured it out 🙏

@thecrypticace It works fine with the latest pre-release (0.13.6). 
Thanks a lot!!!

**Comment by FAHIM-33** [comment]
Man I was going crazy for this issue. After all the struggle, switching to an older version worked fine.  Latest version also doesn't work on linux (Zorin OS in my case.)

**Comment by thecrypticace** [comment]
@FAHIM-33 You're having problems on Windows _and_ linux? Can you open a separate issue with details and logs please?

**Comment by anay-208** [comment]
Hey there,
Even I m facing this issue, Here is my output logs:
```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
[Global] Creating projects: [{"folder":"C:\\Users\\Anay\\documents\\folder","config":"C:/Users/Anay/Documents/folder/cms/tailwind.config.ts","selectors":[{"pattern":"C:/Users/Anay/Documents/folder/cms/tailwind.config.ts","priority":0},{"pattern":"C:/Users/Anay/Documents/folder/cms/**","priority":3}],"user":false,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"C:\\Users\\Anay\\documents\\folder","config":"C:/Users/Anay/Documents/folder/main/tailwind.config.ts","selectors":[{"pattern":"C:/Users/Anay/Documents/folder/main/tailwind.config.ts","priority":0},{"pattern":"C:/Users/Anay/Documents/folder/main/**","priority":3}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Adding watch patterns: C:/Users/Anay/Documents/folder/cms/tailwind.config.ts, C:/Users/Anay/Documents/folder/cms, C:/Users/Anay/Documents/folder, C:/Users/Anay/Documents, C:/Users/Anay, C:/Users, C:/, C:/Users/Anay/Documents/folder/cms/tailwind.config.ts, C:/Users/Anay/Documents/folder/cms, C:/Users/Anay/Documents/folder, C:/Users/Anay/Documents, C:/Users/Anay, C:/Users, C:/
[Global] Adding watch patterns: C:/Users/Anay/Documents/folder/main/tailwind.config.ts, C:/Users/Anay/Documents/folder/main, C:/Users/Anay/Documents/folder/main/tailwind.config.ts, C:/Users/Anay/Documents/folder/main
[Global] Initializing projects...
[Global] Initialized 0 projects
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
{"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}
[Global] Creating projects: [{"folder":"C:\\Users\\Anay\\documents\\folder","config":"C:/Users/Anay/Documents/folder/cms/tailwind.config.ts","selectors":[{"pattern":"C:/Users/Anay/Documents/folder/cms/tailwind.config.ts","priority":0},{"pattern":"C:/Users/Anay/Documents/folder/cms/**","priority":3}],"user":false,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}},{"folder":"C:\\Users\\Anay\\documents\\folder","config":"C:/Users/Anay/Documents/folder/main/tailwind.config.ts","selectors":[{"pattern":"C:/Users/Anay/Documents/folder/main/tailwind.config.ts","priority":0},{"pattern":"C:/Users/Anay/Documents/folder/main/**","priority":3}],"user":false,"tailwind":{"version":"3.4.3","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Adding watch patterns: C:/Users/Anay/Documents/folder/cms/tailwind.config.ts, C:/Users/Anay/Documents/folder/cms, C:/Users/Anay/Documents/folder, C:/Users/Anay/Documents, C:/Users/Anay, C:/Users, C:/, C:/Users/Anay/Documents/folder/cms/tailwind.config.ts, C:/Users/Anay/Documents/folder/cms, C:/Users/Anay/Documents/folder, C:/Users/Anay/Documents, C:/Users/Anay, C:/Users, C:/
[Global] Adding watch patterns: C:/Users/Anay/Documents/folder/main/tailwind.config.ts, C:/Users/Anay/Documents/folder/main, C:/Users/Anay/Documents/folder/main/tailwind.config.ts, C:/Users/Anay/Documents/folder/main
[Global] Initializing projects...
[Global] Initialized 0 projects
```

I m trying the whole day to find a solution, and thought of creating a issue and finally found this.

Let me know if you need any other info

**Comment by anay-208** [comment]
@thecrypticace I tried installing version `v0.13.6 (pre-release)`.
But no luck. Which version should I install.

My OS is windows 11

**Comment by anay-208** [comment]
`v0.12.2` Doesn't seem to be working. what version should I use?

**Comment by anay-208** [comment]
`0.13.8` or `0.13.6` also doesn't work.

**Comment by anay-208** [comment]
`v0.10.5` work perfectly fine. Please let me know if you want output logs of any other version

**Comment by SomeAB** [comment]
I have tried the pre-releases `0.13.x` and everything in `0.12.x` series. Nothing works. 

Currently on `0.10.5` , but intellisense is working pretty slow. 

Plus, there are times when giving a particular class to tag breaks everything. For example, I gave `my-3` to a tag that had `my-2` & `my-4` working, and the browser just didn't render it (even though watch script is working fine seemingly)

**Comment by JasonHassold** [comment]
I'm on a Mac and I believe I'm running into this problem too. I have tested all of the `v0.12` versions and just tried the `v0.13.8 (pre-release)` version and none of those work, but `v0.10.5` works. 

I have sort of a weird setup where I have 2 tailwind.config.js files, one for the main project but it is nested inside a folder called apps/ and then another that is for a specific sub-project in another folder that is all self-contained inside the main project. I was using `"tailwindCSS.experimental.configFile": "./apps/tailwind.config.js"` in my settings.json file to select the right config for the workspace when I'm in `v0.10.5` otherwise the extension won't work properly and this is how I've had the project setup for awhile.

```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"/Users/jasonhassold/Documents/GitHub/[project]","config":"/Users/jasonhassold/Documents/GitHub/[project]/apps/tailwind.config.js","selectors":[{"priority":0,"pattern":"/Users/jasonhassold/Documents/GitHub/[project]/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Adding watch patterns: /Users/jasonhassold/Documents/GitHub/[project]/apps/tailwind.config.js, /Users/jasonhassold/Documents/GitHub/[project]/apps, /Users/jasonhassold/Documents/GitHub/([project]
[Global] Initializing projects...
[Global] Initialized 0 projects
```

**Comment by thecrypticace** [comment]
@JasonHassold Mind updating to the latest pre-release and posting the logs. I suspect it's somehow related to the document you have open not matching the project's "selectors"

**Comment by JasonHassold** [comment]
@thecrypticace this is on `v0.13.8`, the output looks the same to me. I can see that there is a newer pre-release version `v0.13.9` but I can't get it to switch to that one.

```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"/Users/jasonhassold/Documents/GitHub/[project]","config":"/Users/jasonhassold/Documents/GitHub/[project]/apps/tailwind.config.js","selectors":[{"priority":0,"pattern":"/Users/jasonhassold/Documents/GitHub/[project]/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config","relative-content-paths","transpiled-configs"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Adding watch patterns: /Users/jasonhassold/Documents/GitHub/[project]/apps/tailwind.config.js, /Users/jasonhassold/Documents/GitHub/[project]/apps, /Users/jasonhassold/Documents/GitHub/[project]
[Global] Initializing projects...
[Global] Initialized 0 projects
```

**Comment by thecrypticace** [comment]
> I can see that there is a newer pre-release version v0.13.9 but I can't get it to switch to that one.

Maybe you need to restart vscode? It's working fine here. The only difference in the two is some additional logging.

Does your project folder have potential special characters in it? Like brackets, parents, curlies, spaces, etc?

**Comment by JasonHassold** [comment]
@thecrypticace yeah it has parentheses, is that an issue?

**Comment by thecrypticace** [comment]
Probably yeah — I should be able to fix that though!

**Comment by JasonHassold** [comment]
@thecrypticace I figured out why I can't install the latest version, I'm using Cursor (vscode fork) and they might be slightly behind so maybe the latest version of the extension is set to use a versions of vscode that Cursor hasn't updated to yet. 

I went back over to vscode and was able to get `v0.13.9` installed. When I have the the parentheses in the folder name it doesn't work and when I removed the parentheses it does work.

**Comment by JasonHassold** [comment]
@thecrypticace I also just confirmed `v0.13.8` is working on Cursor without the parentheses in the folder name

**Comment by thecrypticace** [comment]
okay cool yeah. I bumped from micromatch to picomatch and I think parens are special there so that was something I missed during the upgrade. I'll see if I can take care of that today. 👍

**Comment by FAHIM-33** [comment]
> @FAHIM-33 You're having problems on Windows _and_ linux? Can you open a separate issue with details and logs (Command Palette > "Tailwind CSS: Show Output") please?

I have opened a new issue as you asked. Here's the link: 
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1008

**Comment by thecrypticace** [comment]
I've released v0.12.4 which addresses some issues with matching documents to a project. Please update and report back.

**Comment by joshuabalentine-PCC** [comment]
@thecrypticace It still doesn't work, but it seems closer:
```
[Global] Initializing projects...
[Info  - 4:08:14 PM] [GLOBAL] Matching project to document {
  fsPath: 'C:\\Users\\JoshuaBalentine\\Source\\[project]\\[path]\\[file].vue',
  normalPath: '/c:/Users/JoshuaBalentine/Source/[project]/[path]/[file].vue'
}
[Global] Initialized 0 projects
...
```

**Comment by erquhart** [comment]
I'm also on Mac and 0.12 broke for me as well, rolled back to v0.10.

I have tried 0.12.4, it did not make any difference that I can see.

When loading, I see the following in output:

This repeated many times:
```
[Info  - 8:06:19 PM] [GLOBAL] Matching project to document {
  fsPath: '/Users/<redacted-base-path>/<redacted-owner>/<redacted-repo>/main/src/ui/<redacted-filename>.tsx',
  normalPath: '/Users/<redacted-base-path>/<redacted-owner>/<redacted-repo>/main/src/ui/<redacted-filename>.tsx'
}
```

Then this shows up in the middle - the remainder of the trace is all lines in the `sucrase` package:
```
[Error - 8:06:19 PM] Tailwind CSS: Unexpected token, expected "{" (14:8)
SyntaxError: Unexpected token, expected "{" (14:8)
    at unexpected (/Users/<redacted-base-path>/<redacted-owner>/<redacted-repo>/main/node_modules/sucrase/dist/parser/traverser/util.js:99:15)
```

Note that whatever error this is referencing, I'm not given a hint on where it's at in my source, assuming it's in my source. But it's also unlikely to be a valid parsing issue, as my linting all runs fine and my project doesn't have any errors.

Then the original thing I pasted about matching project document prints a bunch more times.

**Comment by erquhart** [comment]
@thecrypticace updated to prerelease, still not working. It would be really great to have more verbose logging in the output, I'm convinced multiple issues are occurring but that's tough to verify without logs.

**Comment by thecrypticace** [comment]
@erquhart Your issue is definitely separate — seems like maybe a syntax error in the config file or one of the required/imported files. The error is thrown by sucrase which we used in `loadConfig` at one point (I think we only use babel now in the latest Tailwind CSS release). I'm a little surprised that downgrading would fix that though.

Mind opening a separate issue with details about your config file?

**Comment by erquhart** [comment]
@thecrypticace I think it's been broken this whole time, just not critically. "Building..." was always the last thing printed - unless that's expected, something was always a bit off. I'll open a separate issue for what I've found.

**Comment by thecrypticace** [comment]
@erquhart Ah! Okay the flow bit helps here I think. I'll look into it. Intellisense shouldn't totally _break_ in the face of an invalid config — but your customizations won't show up of course and custom content paths won't be considered.

**Comment by thecrypticace** [comment]
@erquhart So I've reproduced this but in my testing it didn't work in v0.10.5 either. I might see if I can improve the status quo but the big problem here is that `twrnc` is not meant to be included in the tailwind config at all — only in your source files.

**Comment by thecrypticace** [comment]
I've release v0.12.5 which should address a lot of issues around windows / linux / macOS with regards to symlinks, mapped drives of network shares, and mounts of virtual hard disks.

**Comment by joshuabalentine-PCC** [comment]
@thecrypticace Success! Thank you!

**Comment by anay-208** [comment]
Thanks, It works perfect!

**Comment by thecrypticace** [comment]
I'm going to close this issue as all problems should be addressed. If you're still encountering issues please open another issue — thanks!

**Comment by erquhart** [comment]
@thecrypticace ah, I was including the `tailwind.ts` file that imports twrnc in my Tailwind config `content`! I excluded it and everything works now, thanks for the hint here.

**Comment by elepner** [comment]
There's a regression on my setup on Windows after updating 0.12.6 to 0.12.7. I get error in the Output ``No matching project for document``. Everything works fine after downgrading to 0.12.6.

**Comment by scibioulian** [comment]
> There's a regression on my setup on Windows after updating 0.12.6 to 0.12.7. I get error in the Output `No matching project for document`. Everything works fine after downgrading to 0.12.6.

Experiencing exactly the same (error and downgrade-solution).

**Comment by JeanLuisTrunmore** [comment]
Me too, I'm getting that error on my VS Code.

**Comment by JeanLuisTrunmore** [comment]
It is adding a `/` before the root of the project, I think there was a leftover from develop process

**Comment by TomRadford** [comment]
> There's a regression on my setup on Windows after updating 0.12.6 to 0.12.7. I get error in the Output `No matching project for document`. Everything works fine after downgrading to 0.12.6.

Same issue here on MacOS:

What version of VS Code are you using?
v1.92.2

What version of Tailwind CSS IntelliSense are you using?
v0.12.7

What version of Tailwind CSS are you using?
v3.4.10

What package manager are you using?
yarn

What operating system are you using?
macOS 14.3

**Comment by luco** [comment]
Same here:
`[Info  - 11:34:16] [GLOBAL] No matching project for document`

Rolling back to 0.10.5 solves for now.

**Comment by ryantando** [comment]
> Same here: `[Info - 11:34:16] [GLOBAL] No matching project for document`
> 
> Rolling back to 0.10.5 solves for now.

I'm using monorepo and this works
